neoforge_121_minecraft_version=1.21.1
neoforge_121_version=21.1.238
neoforge_121_version_range=[21.1,)
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
mod_id=petiteinventory
mod_name=PetiteInventory
mod_license=AGPL-3.0-only
mod_version=1.1.1
mod_group_id=com.sighs
mod_authors=MerrySnow
mod_description=Minecraft NeoForge modular grid inventory with configurable item footprints and container adapters.
